Modul 1 praktikum datamining
Manipulasi array menggunakan numpy


KODE 1


1   import numpy

2   arr = numpy.array([1, 2, 3, 4, 5])

3	print(arr)

a.	Jelaskan fungsi dari library numpy

    -> Numpy (numerical python) merupakan library yang memudahkan dalam pendefinisian array (1D, 2D, 3D atau nD) dan digunakan untuk komputasi aljabar linier.

b.	Jelaskan perbedaan numpy dengan list pada python
    
    ->Perbedaannya adalah Array harus dideklarasikan terlebih dahulu apakah dia di bawah modul array atau package numpy, sedangkan list tidak perlu. Itulah mengapa list lebih sering digunakan jika dibandingkan array. Perbedaan lainnya adalah array lebih handal dan efisien dalam menyimpan data yang begitu compact. Selain itu, array juga lebih unggul untuk operasi numerik.

c.	Jelakan tentang ndarray
   
    -> NumPy is used to work with arrays. The array object in NumPy is called ndarray.  We can create a NumPy ndarray object by using the array() function.

d.	Jelakan fungsi baris 1
    
    -> Memanggil library Numpy

e.	Jelakan fungsi baris 2

    -> pendeklarasian ndarrray dengan nama arr


f. Buatlah array 2D berikut menggunakan numpy

[4	4	5]

[7	6	4]

[9	7	4]

[6	3	7]


In [5]:
import numpy as np

arr = np.array([[4,4,5], [7,6,4], [9,7,4], [6,3,7]])

print(arr)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


g. Buatlah array 3D berikut menggunakan numpy

[7	8	5]	    	[2	1	2]		    [2	9	3]

[4	7	7]	    	[9	8	5]		    [2	4	8]

[7	1	9]	    	[3	7	3]		    [1	6	6]

[5	4	10]	    	[4	9	9]		    [8	1	3]


In [6]:
import numpy as np

arr = np.array([[[7,8,5], [4,7,7], [7,1,9], [5,4,10]], [[2,1,2], [9,8,5], [3,7,3], [4,9,9]], [[2,9,3], [2,4,8], [1,6,6], [8,1,3]]])

print(arr)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


Kode 2

Jalankan kode berikut

1   import numpy as np

2   arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

3   print(arr[0, 1, 2])

4

5   import numpy as np

6   arr = np.array([1, 2, 3, 4, 5, 6, 7])

7   print(arr[:4])

8   import numpy as np

9   arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

10  print(arr[0:2, 2])

a. Jelaskan cara mengakses elemen array seperti kode pada baris 3

    -> Pada kode baris ke-2 menunjukkan bahwa array 3D. 
    Pada kode baris ke-3 menampilkan array pada kode baris ke-2 array level pertama mengambil pada indeks ke-0,
    Lalu mengambil level array ke-2 pada indeks ke-1 yaitu menunjukkan array [4,5,6]
    Lalu mengambil level array ke-3 pada indeks ke-2 yaitu menunjukkan array level sebelumya dan didapatkan output 6 

b. Jelaskan cara mengakses elemen array seperti kode pada baris 7

    -> Pada kode baris ke-6 menunjukkan bahwa array 1D.
    Pada kode baris ke-7 menampilkan array mulai dari indeks ke-0 hingga ke indeks ke-3 sehingga mendapatkan output [1 2 3 4]
    dan indeks ke-4 tidak dimasukkan ke output karena itu merupakan batas atas


c. Jelaskan cara mengakses elemen array seperti kode pada baris 10

    -> Pada kode baris ke-9 menunjukkan bahwa array 2D. 
    Pada kode baris ke-10 menampilkan array pada kode baris ke-9 array level pertama mengambil pada indeks ke-0 hingga indeks ke-1 dan indeks ke-2 tidak ditampilkan karena itu hanya menjadi batas atas,
    Lalu mengambil array level ke-2 pada indeks ke-2 dan menunjukkan output [3 8]


d.	Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut.

[1	8	8	2]

[8	2	1	2]

[10	1	4	7]

[1	4	7	8]

[8	2	3	4]


In [36]:
import numpy as  np

arr = np.array([[1,8,8,2], [8,2,1,2], [10,1,4,7], [1,4,7,8], [8,2,3,4]])

arr[::2, :] +=1
arr[:, 1::2] +=2

arr

array([[ 1,  8,  8,  2],
       [10,  1,  4,  7],
       [ 8,  2,  3,  4]])

e. Baliklah sumbu z array 3D berikut

[7	8	5]		[2	1	2]		[2	9	3]

[4	7	7]		[9	8	5]		[2	4	8]

[7	1	9]		[3	7	3]		[1	6	6]

[5	4	10]		[4	9	9]		[8	1	3]


In [26]:
import numpy as np

arr = np.array([[[7,8,5], [4,7,7], [7,1,9], [5,4,10]], [[2,1,2], [9,8,5], [3,7,3], [4,9,9]], [[2,9,3], [2,4,8], [1,6,6], [8,1,3]]])

arr[::-1, :, :]


array([[[ 2,  9,  3],
        [ 2,  4,  8],
        [ 1,  6,  6],
        [ 8,  1,  3]],

       [[ 2,  1,  2],
        [ 9,  8,  5],
        [ 3,  7,  3],
        [ 4,  9,  9]],

       [[ 7,  8,  5],
        [ 4,  7,  7],
        [ 7,  1,  9],
        [ 5,  4, 10]]])

f.	Ubahlah array pada soal e menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah	 reshape)

In [4]:
import numpy as np

arr = np.array([[[7,8,5], [4,7,7], [7,1,9], [5,4,10]], [[2,1,2], [9,8,5], [3,7,3], [4,9,9]], [[2,9,3], [2,4,8], [1,6,6], [8,1,3]]])

print(np.reshape(arr, (6,6)))


[[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


Kode 3

Jalankan kode berikut

1   import numpy as np

2   arr1 = np.array([[1, 2], [3, 4]])

3   arr2 = np.array([[5, 6], [7, 8]])

4   arr = np.concatenate((arr1, arr2), axis=1)

5   print(arr)

6   

7   import numpy as np

8   arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

9   newarr = np.array_split(arr, 3, axis=1)

10	print(newarr)


a.	Jelaskan apa yang dilakukan di baris 3

    -> pada baris ketiga mendeklarasikan arr2 dengan array 2 dimesi yaitu [5, 6], [7, 8]

b.	Gantilah nilai axis menjadi 0. Jelaskan apa yang terjadi

    ->karna akan membuat yang sebelumnya terdapat 2 array 1d, menjadi 4 array 1 d dalam 1 array 2d

c.	Jelaskan apa yang dilakukan di baris 9

    ->

d.	Gantilah nilai axis menjadi 0. Jelaskan apa yang terjadi

    ->


In [65]:
import numpy as np
arr = np.array(
    [[5,10,10,7],
     [7,8,4,10],
     [9,10,2,5], 
     [1,8,9,3], 
     [6,10,5,2], 
     [4,6,9,4]])

y = np.array_split(arr, 2, axis =0)[::-1]
y1 = np.concatenate(y,axis=0)

x = np.array_split(y1, 2, axis=1)[::-1]
x1 = np.concatenate(x, axis=1)


x1

array([[ 9,  3,  1,  8],
       [ 5,  2,  6, 10],
       [ 9,  4,  4,  6],
       [10,  7,  5, 10],
       [ 4, 10,  7,  8],
       [ 2,  5,  9, 10]])