Modul 1 praktikum datamining

Manipulasi array menggunakan numpy

FRANS VITO JONATHAN SIMAMORA

202410101147

DATAMINING A

In [59]:
import numpy as np

In [61]:
arr = np.array([[4,4,5], [7,6,4], [9,7,4], [6,3,7]])

arr

array([[4, 4, 5],
       [7, 6, 4],
       [9, 7, 4],
       [6, 3, 7]])

In [62]:
arr = np.array([
    [[7,8,5],
    [4,7,7],
    [7,1,9],
    [5,4,10]],
    
    [[2,1,2],
    [9,8,5],
    [3,7,3],
    [4,9,9],],

    [[2,9,3],
    [2,4,8],
    [1,6,6],
    [8,1,3]]
])

arr

array([[[ 7,  8,  5],
        [ 4,  7,  7],
        [ 7,  1,  9],
        [ 5,  4, 10]],

       [[ 2,  1,  2],
        [ 9,  8,  5],
        [ 3,  7,  3],
        [ 4,  9,  9]],

       [[ 2,  9,  3],
        [ 2,  4,  8],
        [ 1,  6,  6],
        [ 8,  1,  3]]])

In [70]:
arr = np.array([
    [1,8,8,2],
    [8,2,1,2],
    [10,1,4,7],
    [1,4,7,8],
    [8,2,3,4]
])

arr[::2, :] +=1
arr[:, 1::2] +=2

arr

array([[ 2, 11,  9,  5],
       [ 8,  4,  1,  4],
       [11,  4,  5, 10],
       [ 1,  6,  7, 10],
       [ 9,  5,  4,  7]])

In [72]:
arr = np.array([
    [[7,8,5],
    [4,7,7],
    [7,1,9],
    [5,4,10]],
    
    [[2,1,2],
    [9,8,5],
    [3,7,3],
    [4,9,9],],

    [[2,9,3],
    [2,4,8],
    [1,6,6],
    [8,1,3]]
])

arr[::-1, :, :]

array([[[ 2,  9,  3],
        [ 2,  4,  8],
        [ 1,  6,  6],
        [ 8,  1,  3]],

       [[ 2,  1,  2],
        [ 9,  8,  5],
        [ 3,  7,  3],
        [ 4,  9,  9]],

       [[ 7,  8,  5],
        [ 4,  7,  7],
        [ 7,  1,  9],
        [ 5,  4, 10]]])

In [78]:
arr = np.array([
    [5,10,10,7],
    [7,8,4,10],
    [9,10,2,5],
    [1,8,9,3],
    [6,10,5,2],
    [4,6,9,4]
])

array = np.array_split(arr,2,axis=1)[::-1]
arrays = np.concatenate(array, axis=1)

x = np.array_split(arrays,2,axis=0)[::-1]
x1 = np.concatenate(x,axis=0)

x1


array([[ 9,  3,  1,  8],
       [ 5,  2,  6, 10],
       [ 9,  4,  4,  6],
       [10,  7,  5, 10],
       [ 4, 10,  7,  8],
       [ 2,  5,  9, 10]])